In [1]:
import pandas as pd
import numpy as np

In [2]:
alameda = pd.read_csv("alamedatwitter_11_5.csv")

In [3]:
len(alameda)

6994566

In [5]:
alameda_sample = alameda.sample(int((1/8)*len(alameda)))

In [6]:
len(alameda_sample)

874320

In [7]:
alameda_sample.head()

,Unnamed: 0,id,u_id,lat,lon,date,tract,home_tract
4028036,27690560,4.535225e-278,1.112537e-308,37.751440,-122.201470,2014-04-19T19:26:50Z,6.001409e+09,6.001401e+09
3632268,25045463,1.642058e-279,1.112537e-308,37.739453,-122.204015,2014-02-19T20:12:24Z,6.001409e+09,6.001409e+09
1836509,12283845,1.334368e-284,1.112537e-308,37.793606,-122.276236,2013-07-25T01:56:25Z,6.001983e+09,6.075062e+09
455853,2888010,3.521321e-291,1.112537e-308,37.804510,-122.272987,2012-10-26T02:09:21Z,6.001403e+09,6.075010e+09
2301197,15618344,2.834528e-283,1.112537e-308,37.872170,-122.271150,2013-09-16T22:17:42Z,6.001422e+09,6.001422e+09

In [8]:
alameda_sample.to_csv("alameda_sample.csv")

In [10]:
alameda_sample_2 = alameda_sample.sample(int(.85*len(alameda_sample)))

In [12]:
len(alameda_sample_2)

743172

In [13]:
alameda_sample_2.to_csv("alameda_sample.csv")

In [34]:
alameda_sample = pd.read_csv("alameda_sample.csv")

In [35]:
alameda_sample.head()

,Unnamed: 0,Unnamed: 0.1,id,u_id,lat,lon,date,tract,home_tract
0,6687538,45549635,2.638238e-270,1.112537e-308,37.704135,-122.088003,2015-03-06T06:23:10Z,6.001431e+09,6.001431e+09
1,1657499,10992369,3.016355e-285,1.112537e-308,37.885946,-122.309281,2013-06-27T20:43:25Z,6.001420e+09,6.013340e+09
2,6405793,43710377,3.626058e-271,1.112537e-308,37.668113,-121.875291,2015-01-29T16:58:49Z,6.001451e+09,6.001451e+09
3,2267007,15376242,3.672158e-283,1.112537e-308,37.665651,-122.079126,2013-09-21T18:23:26Z,6.001436e+09,6.001436e+09
4,554362,3493962,8.446129e-291,1.112537e-308,37.634858,-122.056420,2012-11-10T05:41:18Z,6.001435e+09,6.001438e+09

In [36]:
len(alameda_sample)

743172

In [37]:
alameda_sample[alameda_sample.isnull().any(axis=1)]

,Unnamed: 0,Unnamed: 0.1,id,u_id,lat,lon,date,tract,home_tract
1585,203115,1275268,5.178454e-292,1.112537e-308,37.822981,-122.241910,2012-09-21T05:10:22Z,6.001426e+09,NaN
17838,6243352,42677078,2.749413e-271,1.112537e-308,37.838668,-122.266042,2015-01-25T02:28:27Z,6.001401e+09,NaN
28064,4451672,30392793,1.459964e-277,1.112537e-308,37.841809,-122.293920,2014-05-10T18:21:15Z,6.001425e+09,NaN
32745,5930127,40652690,1.904475e-272,1.112537e-308,37.809338,-122.272779,2014-12-07T22:57:37Z,6.001403e+09,NaN
56028,3134045,21516927,4.323043e-280,1.112537e-308,37.865808,-122.314739,2014-01-27T05:10:34Z,6.001422e+09,NaN
64843,4540043,30960839,1.471807e-277,1.112537e-308,37.651870,-122.090782,2014-05-10T21:29:06Z,6.001437e+09,NaN
75172,2466461,16780499,2.343310e-282,1.112537e-308,37.741463,-122.210142,2013-10-24T18:11:33Z,6.001409e+09,NaN
85882,2465907,16775782,2.492858e-282,1.112537e-308,37.742672,-122.211464,2013-10-25T20:06:07Z,6.001409e+09,NaN
106298,459127,2909260,4.973701e-291,1.112537e-308,37.844806,-122.291376,2012-10-31T17:14:44Z,6.001425e+09,NaN
127289,356399,2254756,2.578300e-291,1.112537e-308,37.794635,-122.252407,2012-10-19T23:59:45Z,6.001405e+09,NaN
137752,3218027,22102230,2.018798e-280,1.112537e-308,37.803545,-122.256718,2014-01-13T04:16:44Z,6.001403e+09,NaN
140115,106610,685009,1.265215e-292,1.112537e-308,37.828965,-122.249261,2012-08-26T23:53:58Z,6.001404e+09,NaN
147595,3110264,21347944,9.741785e-281,1.112537e-308,37.819559,-122.244679,2013-12-30T22:56:55Z,6.001426e+09,NaN
156051,4321416,29541280,1.585184e-277,1.112537e-308,37.642435,-122.059391,2014-05-12T03:27:26Z,6.001438e+09,NaN
193861,1811574,12108049,1.237727e-284,1.112537e-308,37.794453,-122.284798,2013-07-23T07:04:40Z,6.001982e+09,NaN
211628,1445013,9502506,3.581308e-286,1.112537e-308,37.822021,-122.311737,2013-05-20T11:05:43Z,6.001402e+09,NaN
214780,2486729,16928523,2.132750e-282,1.112537e-308,37.742672,-122.211464,2013-10-23T05:42:47Z,6.001409e+09,NaN
225075,2439746,16587336,2.131020e-282,1.112537e-308,37.742672,-122.211464,2013-10-23T05:24:48Z,6.001409e+09,NaN
233379,5094696,34850006,6.745725e-276,1.112537e-308,37.825269,-122.247586,2014-07-19T00:59:11Z,6.001426e+09,NaN
242829,2563684,17465181,9.997851e-283,1.112537e-308,37.768408,-122.277439,2013-10-09T20:22:41Z,6.001429e+09,NaN
248587,5424828,37164037,5.690160e-275,1.112537e-308,37.825082,-122.309644,2014-08-26T14:05:16Z,6.001402e+09,NaN
248645,1812458,12113915,1.241252e-284,1.112537e-308,37.792240,-122.285706,2013-07-23T08:38:28Z,6.001429e+09,NaN
254435,6697618,45616917,9.953024e-270,1.112537e-308,37.835488,-122.271395,2015-03-30T03:16:36Z,6.001401e+09,NaN
273427,3719305,25637518,4.690665e-279,1.112537e-308,37.803545,-122.256718,2014-03-10T01:53:51Z,6.001403e+09,NaN
284405,2044326,13771668,1.056544e-283,1.112537e-308,37.798061,-122.263879,2013-08-31T02:39:16Z,6.001403e+09,NaN
302659,1817481,12148627,1.302428e-284,1.112537e-308,37.821758,-122.311256,2013-07-24T11:46:27Z,6.001402e+09,NaN
306966,5407939,37039997,5.855009e-275,1.112537e-308,37.579895,-122.004432,2014-08-27T03:03:49Z,6.001441e+09,NaN
307558,1098448,7074535,1.413357e-287,1.112537e-308,37.826683,-122.239155,2013-03-23T22:42:54Z,6.001426e+09,NaN
315380,6667082,45412095,3.080874e-270,1.112537e-308,37.835887,-122.262732,2015-03-09T04:07:56Z,6.001401e+09,NaN
317071,2736343,18677079,1.250872e-281,1.112537e-308,37.803545,-122.256718,2013-11-24T06:31:18Z,6.001403e+09,NaN
...,...,...,...,...,...,...,...,...,...
513403,3472237,23895174,6.044104e-280,1.112537e-308,37.803866,-122.272398,2014-02-01T07:20:48Z,6.001403e+09,NaN
514259,6135966,42001955,3.300668e-272,1.112537e-308,37.788362,-122.251928,2014-12-18T05:57:51Z,6.001406e+09,NaN
514334,1193080,7749709,2.248942e-287,1.112537e-308,37.704772,-121.876032,2013-03-31T20:27:41Z,6.001450e+09,NaN
517295,1099902,7084723,4.801073e-288,1.112537e-308,37.833802,-122.292300,2013-03-03T21:20:20Z,6.001425e+09,NaN
521360,2447399,16638634,2.222723e-282,1.112537e-308,37.742672,-122.211464,2013-10-23T21:18:03Z,6.001409e+09,NaN
526647,1023747,6525891,2.033921e-288,1.112537e-308,37.821613,-122.310478,2013-02-16T16:28:32Z,6.001402e+09,NaN
537336,6585241,44873012,6.163226e-271,1.112537e-308,37.867670,-122.312500,2015-02-08T06:36:41Z,6.001422e+09,NaN
540978,3125061,21453800,2.005621e-280,1.112537e-308,37.796144,-122.277188,2014-01-13T00:42:43Z,6.001983e+09,NaN
541394,68292,441367,1.278034e-293,1.112537e-308,37.823028,-122.243261,2012-07-17T16:51:03Z,6.001426e+09,NaN
555826,2458653,16720844,1.815660e-282,1.112537e-308,37.742672,-122.211464,2013-10-20T22:46:38Z,6.001409e+09,NaN
559314,2455868,16701103,1.947481e-282,1.112537e-308,37.742672,-122.211464,2013-10-21T21:36:55Z,6.001409e+09,NaN
578210,2522543,17176663,1.271169e-282,1.112537e-308,37.794563,-122.277023,2013-10-13T18:24:46Z,6.001983e+09,NaN
579595,46953,304565,6.197469e-294,1.112537e-308,37.823915,-122.239766,2012-07-04T18:17:25Z,6.001426e+09,NaN
582830,6690088,45566258,2.472229e-270,1.112537e-308,37.800488,-122.270090,2015-03-05T04:13:41Z,6.001403e+09,NaN
585902,2436835,16567839,2.099611e-282,1.112537e-308,37.742672,-122.211464,2013-10-22T23:58:19Z,6.001409e+09,NaN
592679,513366,3246440,8.705408e-291,1.112537e-308,37.826683,-122.239155,2012-11-10T17:44:47Z,6.001426e+09,NaN
595269,103017,662963,6.568946e-293,1.112537e-308,37.750290,-122.202945,2012-08-15T04:05:44Z,6.001409e+09,NaN
596114,5718517,39230836,5.314680e-274,1.112537e-308,37.710775,-122.216410,2014-10-05T02:33:09Z,6.001409e+09,NaN
630624,2469050,16799210,2.509988e-282,1.112537e-308,37.742672,-122.211464,2013-10-25T23:04:11Z,6.001409e+09,NaN
631443,2442762,16608870,2.205636e-282,1.112537e-308,37.742038,-122.209037,2013-10-23T18:20:27Z,6.001409e+09,NaN
635943,375055,2373720,3.019609e-291,1.112537e-308,37.606953,-122.141182,2012-10-23T10:05:27Z,6.001437e+09,NaN
653331,2443702,16614955,2.132739e-282,1.112537e-308,37.742672,-122.211464,2013-10-23T05:42:40Z,6.001409e+09,NaN
659915,2626044,17903197,2.521440e-282,1.112537e-308,37.742672,-122.211464,2013-10-26T01:03:13Z,6.001409e+09,NaN
662722,3336894,22928412,1.071760e-280,1.112537e-308,37.803545,-122.256718,2014-01-02T03:46:47Z,6.001403e+09,NaN
690990,3257591,22374327,1.804919e-280,1.112537e-308,37.839651,-122.269584,2014-01-10T18:22:52Z,6.001401e+09,NaN
695084,4880443,33348412,2.246850e-276,1.112537e-308,37.636616,-122.054775,2014-06-28T20:40:49Z,6.001438e+09,NaN
706343,4720029,32226190,4.888135e-277,1.112537e-308,37.654590,-122.055470,2014-06-01T23:58:42Z,6.001435e+09,NaN
712035,216220,1361321,6.077702e-292,1.112537e-308,37.870644,-122.259690,2012-09-24T00:05:10Z,6.001423e+09,NaN
735758,3631297,25038500,1.627594e-279,1.112537e-308,37.806978,-122.255859,2014-02-19T15:18:44Z,6.001403e+09,NaN
738368,6630468,45170046,1.856051e-270,1.112537e-308,37.812862,-122.246851,2015-02-28T21:20:00Z,6.001404e+09,NaN

In [38]:
alameda_sample = alameda_sample.dropna(axis=0, how='any')

In [39]:
len(alameda_sample)

743091

In [40]:
alameda_sample[alameda_sample.isnull().any(axis=1)]

Empty DataFrame
Columns: [Unnamed: 0, Unnamed: 0.1, id, u_id, lat, lon, date, tract, home_tract]
Index: []

In [29]:
len(alameda_sample)

743066