In [18]:
# Libraries that this notebook will use:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#from geopandas import GeoDataFrame
from shapely.geometry import Point
# Help the maps display nicely in the notebook:
%matplotlib inline
plt.rcParams['figure.figsize'] = [30, 20]
# Tells the notebook not to display warnings:
import warnings
warnings.filterwarnings('ignore')

# Working with large datasets + visualizations
## Data cleaning

In [12]:
alameda = pd.read_csv("alameda_sample.csv")
alameda.head()

,Unnamed: 0,Unnamed: 0.1,id,u_id,lat,lon,date,tract,home_tract
0,6687538,45549635,2.638238e-270,1.112537e-308,37.704135,-122.088003,2015-03-06T06:23:10Z,6.001431e+09,6.001431e+09
1,1657499,10992369,3.016355e-285,1.112537e-308,37.885946,-122.309281,2013-06-27T20:43:25Z,6.001420e+09,6.013340e+09
2,6405793,43710377,3.626058e-271,1.112537e-308,37.668113,-121.875291,2015-01-29T16:58:49Z,6.001451e+09,6.001451e+09
3,2267007,15376242,3.672158e-283,1.112537e-308,37.665651,-122.079126,2013-09-21T18:23:26Z,6.001436e+09,6.001436e+09
4,554362,3493962,8.446129e-291,1.112537e-308,37.634858,-122.056420,2012-11-10T05:41:18Z,6.001435e+09,6.001438e+09

In [13]:
len(alameda)

743172

In [14]:
# Clean the dataset of missing values
# Display rows with missing values in any column. There are a total of 81.
alameda[alameda.isnull().any(axis=1)].head()

,Unnamed: 0,Unnamed: 0.1,id,u_id,lat,lon,date,tract,home_tract
1585,203115,1275268,5.178454e-292,1.112537e-308,37.822981,-122.241910,2012-09-21T05:10:22Z,6.001426e+09,NaN
17838,6243352,42677078,2.749413e-271,1.112537e-308,37.838668,-122.266042,2015-01-25T02:28:27Z,6.001401e+09,NaN
28064,4451672,30392793,1.459964e-277,1.112537e-308,37.841809,-122.293920,2014-05-10T18:21:15Z,6.001425e+09,NaN
32745,5930127,40652690,1.904475e-272,1.112537e-308,37.809338,-122.272779,2014-12-07T22:57:37Z,6.001403e+09,NaN
56028,3134045,21516927,4.323043e-280,1.112537e-308,37.865808,-122.314739,2014-01-27T05:10:34Z,6.001422e+09,NaN

In [15]:
# Get rid of the rows where home_tract is NaN
# This code actually drops any row where there is a missing value in any column, not just home_tract 
alameda = alameda.dropna(axis=0, how='any')
len(alameda)

743091

In [16]:
# Now if you check for rows with missing values:
alameda[alameda.isnull().any(axis=1)]

Empty DataFrame
Columns: [Unnamed: 0, Unnamed: 0.1, id, u_id, lat, lon, date, tract, home_tract]
Index: []

## Grouping data

In [23]:
alameda.groupby(by=["tract"], axis=1).count()

ValueError: operands could not be broadcast together with shapes (9,) (743091,8)

In [ ]:
# Geoframe conversion: https://gis.stackexchange.com/questions/174159/convert-a-pandas-dataframe-to-a-geodataframe